### ISSUE TITLE
I'm back :)

### ISSUE THREAD

**Issue by andreyorst** [jdugan6240/powerline.kak#13]
I'm back and able to continue maintainance of plugins. If you want you can submit a pull request with your canges and I will continue from that point, or I can do this manually, unless you'd like to keep maintaining this fork

**Comment by jdugan6240** [comment]
Welcome back! It has been a genuine pleasure working on your plugin for this short time.

I think submitting a pull request would be the best approach. Performing all the changes manually just sounds like a hassle IMO, so that would probably make the transition easier.

As for maintaining this fork - I was thinking of doing a complete rewrite of powerline.kak to try to simplify the modular system (this would necessarily come at the cost of sacrificing some features, such as the autocomplete support). To avoid the confusion issues with both plug.kak's, this would probably be under a different name (like kak-airline or something).

Needless to say that I don't think I'll be keeping this fork up once the changes are merged into your original repo. I'd still like to contribute pull requests every once in a while, though 🙂.

**Comment by andreyorst** [comment]
Great! That settles it then! :)
